### ISSUE TITLE
Some functions not rendered in docs

### ISSUE THREAD

**Issue by malankriel** [AutoActuary/mkdocstrings-vba#2]
Given these two functions in the .bas file:
![image](https://user-images.githubusercontent.com/51300197/154965011-6a8c41ee-c098-4256-84ff-cff127d637bc.png)

Only the Private function is in the documentation:
![image](https://user-images.githubusercontent.com/51300197/154965107-ff2e4585-1e6f-49e7-9ac9-e3557f06ea7c.png)

**Comment by malankriel** [comment]
Looks like we try to though:
https://github.com/AutoActuary/mkdocstrings-vba/blob/2709106aee2b80371a7bbf5c48f18adc648cf7f8/mkdocstrings_handlers/vba/util.py#L139

**Comment by malankriel** [comment]
Nothing to do with Private / Public, I'm working on MWE now

**Comment by malankriel** [comment]
Okay, so this doesn't render:
```
Function dictget(d As Dictionary, key As Variant, Optional default As Variant = Empty)
    
End Function
```
But this does:
```
Function dictget(d As Dictionary, key As Variant)
    
End Function
```

**Comment by malankriel** [comment]
```
' Variant tests:
Function Test1(d As Dictionary, key As Variant, Optional default As Variant = Empty)
    ' This doesn't render
End Function

Function Test2(d As Dictionary, key As Variant, Optional default As Variant)
    ' This renders
End Function

Function Test3(d As Dictionary, key As Variant, Optional default)
    ' This renders
End Function


' Integer tests:
Function Test4(d As Dictionary, key As Variant, Optional default As Integer = 0)
    ' This doesn't render
End Function

Function Test5(d As Dictionary, key As Variant, Optional default As Integer)
    ' This renders
End Function

Function Test6(d As Dictionary, key As Variant, Optional default)
    ' This renders
End Function
```

It looks like any optional argument with a default value doesn't render

**Comment by malankriel** [comment]
Another one that doesn't render:
```
Public Function dict(ParamArray Args() As Variant) As Dictionary

End Function
```

**Comment by rudolfbyker** [comment]
Sorry, I just made a single commit that closes the issue, rather than a PR, since this module is still so experimental
