### ISSUE TITLE
ParamArray doesn't render in docs

### ISSUE THREAD

**Issue by malankriel** [AutoActuary/mkdocstrings-vba#3]
```
Function dict(ParamArray Args() As Variant)

End Function
```

Moved from here: 
_Originally posted by @malankriel in https://github.com/AutoActuary/mkdocstrings-vba/issues/2#issuecomment-1046927131_

**Comment by rudolfbyker** [comment]
- What is `ParamArray`?
- Is the name of the argument `Args` or `Args()`? If the former, what does the `()` mean?

**Comment by malankriel** [comment]
> * What is `ParamArray`?
> * Is the name of the argument `Args` or `Args()`? If the former, what does the `()` mean?

https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/understanding-parameter-arrays

**Comment by malankriel** [comment]
> > * What is `ParamArray`?
> > * Is the name of the argument `Args` or `Args()`? If the former, what does the `()` mean?
> 
> https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/understanding-parameter-arrays

`ParamArray` is a VBA keyword to indicate you are now specifying an "array" parameter.
The name is is `Args`, but the `()` means that `Args` is an array and not just a scalar/object. You cannot specify: `ParamArray Args` without the `()`
